### PR TITLE
docs: add docs for numerical filters

### PR DESCRIPTION
**Pull request by yeforriak**
Add docs for range numerical filters.

### CODE REVIEW

**Review by jgresty — APPROVED** [review]
It might be difficult to explain this in our public documentation since support will be different per query parameter. If this is something you are going to support in your endpoint it may be worth laying down some recommendations around that area too.

**Comment by jgresty** [comment]
Also an example would be highly appreciated

**Comment by yeforriak** [comment]
> Also an example would be highly appreciated

yes definitely!. I added a quick example:
```
For example, the `count` property can also be used as a range filtering value via `count_gt` or `count_lt` for `count` values greater than or less than the provided filter values
```
is it clear? should I rephrase it? or change the format?

**Comment by jgresty** [comment]
> is it clear? should I rephrase it? or change the format?

That is clear, I was thinking about an example query, eg:
```http
GET https://example.com/foos?count_lt=5
```

**Comment by yeforriak** [comment]
> > is it clear? should I rephrase it? or change the format?
> 
> That is clear, I was thinking about an example query, eg:
> 
> ```httpspec
> GET https://example.com/foos?count_lt=5
> ```

Gotcha, yes good idea. I just added it. Thanks

**Comment by yeforriak** [comment]
> It might be difficult to explain this in our public documentation since support will be different per query parameter. If this is something you are going to support in your endpoint it may be worth laying down some recommendations around that area too

yes, that is a good idea. 
I didn't start with the implementation yet, but as soon as I make some progress I can follow up with a different PR and share some recommendations.

**Pull request merged**
