### PR TITLE
Update JSON API docs

### PR DESCRIPTION
**Pull request by acunniffe**
[todo] finish the updating links to correct ones in sweater comb

### CODE REVIEW

**Review by cmars — APPROVED** [review]

**Comment by cmars** [comment]
Looks good, just needs a `yarn run format` I think. Thanks for this!

**Comment by acunniffe** [comment]
Hmm it's not working. Very weird. Lm try a few things.

**Comment by cmars** [comment]
I misread the CircleCI error -- it's commitlint. The commit tag `input:` isn't in the allowlist ("feat", "fix", "docs", "chore", "refactor", "test", "revert").

**Comment by cmars** [comment]
I'd recommend a `git rebase -i origin/main` and change the commit header to `fix: update JSON API docs`.

Sorry about the confusion here -- I introduced commitlint to ensure we don't break semantic-releases in our build. Tbf I wasn't a huge fan of conventional commits, but I've come around to being a fan of the way it automates tagging and releases for us.

**Comment by cmars** [comment]
Rebased and merged in #182

**Pull request closed without merging**
