### PR TITLE
Made workflow interface a lot nicer for users

### PR DESCRIPTION
**Pull request by acunniffe**
Cleaned up a lot of the initial usability feedback from @cmars that was shared in slack
- Can be run from the same directory as `resources` or any sub dir (just like .git or npm scripts)
- Instead of providing a file to `workflow operation` you just specify `[resource] [version]` where version can be left out to default to `latest`. 
- Paths are lower case now
- You only need to specify the singular and plural forms when creating the resource, they are remembered in your spec using extensions in `info`. 

Other PRs will come monday to enable the example update script and make error messages more readable.

### CODE REVIEW

**Comment by acunniffe** [comment]
Expanded to include: 
- Nicer logging 
Screen Shot 2022-03-20 at 11 17 58 AM
- Clickable links to the spec YAML :) 
- a `version` workflow `sweater-comb  workflow version issues beta`

**Comment by JaapRood** [comment]
I've expanded this yet a bit further by adding the `update` command to the CLI. As configured now the command would be `sweater-comb update <path-to-file>`. Hope that's alright, also happy to open a separate PR if that's preferred.

We've deemed a flag for 'examples' not necessary for now: at the time of writing, the only way to update is by the examples, and even as we add different traffic sources support to the commands, by-example is likely to stay remain the default (as all others require extra configuration). That said, it's yet another `Commander` instance, so the command can be called anything and accept additional flags.

The one thing that the command doesn't currently support is the rest of the path resolving logic that was added in the rest of this PR. Since this taps right into the command as generated for Optic's own CLI, we'll have to take a moment to figure out how to enable that, if preferred. Happy to follow up with that later, if this PR is merged in the meantime.

**Comment by cmars** [comment]
Doing some manual QA now to smoke test.

**Comment by cmars** [comment]
I found it surprising that the `update` command isn't a sub-command of workflow. Isn't it part of the OpenAPI authoring workflow?

It also doesn't seem to work; I added an example to the initial resource attributes schema, ran `update`, but nothing changed.

Screen Shot 2022-03-21 at 8 47 53 AM

**Comment by cmars** [comment]
Re-running `workflow operation add-create` throws an uncaught exception:
```
zksnyk:api cmars$ sweater-comb workflow operation add-create `pwd`/resources/tests/2022-03-21/spec.yaml test tests
zksnyk:api cmars$ sweater-comb workflow operation add-create `pwd`/resources/tests/2022-03-21/spec.yaml test tests
(node:39512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '500' of undefined
    at applyOperation (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/fast-json-patch/commonjs/core.js:240:22)
    at Object.applyPatch (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/fast-json-patch/commonjs/core.js:278:22)
    at /Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:54:53
    at step (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:33:23)
    at Object.next (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:14:53)
    at /Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:4:12)
    at applyPatch (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/reconcilers/stringify.js:48:12)
    at Function.<anonymous> (/Users/cmars/.fnm/node-versions/v14.17.1/installation/lib/node_modules/@snyk/sweater-comb/node_modules/@useoptic/openapi-cli/build/specs/files/index.js:53:79)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:39512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by acunniffe** [comment]
Follow up from meeting & review 

optic is working on
- fixing design-by-example
- end-end testing 
- making commands and arguments discoverable so there are fewer rough edges for end-users to potentially hit

**Review by cmars — APPROVED** [review]
I'm +1 to land this and iterate as discussed.

**Pull request merged**
